const UPDATE_CART = "UPDATE_CART";
const UPDATE_PRICE = "UPDATE_PRICE";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const CHANGE_CATEGORY = "CHANGE_CATEGORY";

export { UPDATE_CART, UPDATE_PRICE, UPDATE_PRODUCT, CHANGE_CATEGORY };