const UPDATE_CART = "UPDATE_CART";
const UPDATE_PRICE = "UPDATE_PRICE";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const CHANGE_CATEGORY = "CHANGE_CATEGORY";
const LOGO_IN = 'LOGO_IN';
const LOG_OUT = 'LOGO_OUT';

export {
  LOG_OUT,
  LOGO_IN,
  UPDATE_CART,
  UPDATE_PRICE,
  UPDATE_PRODUCT,
  CHANGE_CATEGORY
};